### ISSUE TITLE
enpass

### ISSUE THREAD

**Issue by samuelbernardo** [zamabe/otovad-overlay#1]
Very nice work with your ebuild for enpass.

I'll adapt it for version 5.3.0 that is released on arch aur, but I note that it's incomplete in term of dependencies:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=enpass-bin

Thanks for sharing your ebuilds ;)

**Comment by zamabe** [comment]
Sorry, I've stopped using enpass and I have forgotten to remove it from my overlay since then. I hope you find it useful if you want to fork it for your own use.

**Comment by samuelbernardo** [comment]
ok, I have shared it in my overlay for the latest version.
No changes were needed from the original ebuild based on 5.0.5:
https://github.com/samuelbernardo/ssnb-overlay/tree/master/app-admin/enpass

thks again
